# Generated by Django 4.0.6 on 2022-08-14 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=30, verbose_name='Апартамент')),
            ],
            options={
                'verbose_name': 'Апартамент',
                'verbose_name_plural': 'Апартаменты',
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.DateField(verbose_name='Заезд')),
                ('departure', models.DateField(verbose_name='Выезд')),
                ('first_name', models.CharField(default='', max_length=60, verbose_name='Имя')),
                ('last_name', models.CharField(default='', max_length=60, verbose_name='Фамилия')),
                ('adults', models.IntegerField(verbose_name='Кол-во взрослых')),
                ('children', models.IntegerField(verbose_name='Кол-во детей')),
                ('infants', models.IntegerField(verbose_name='Кол-во младенцев')),
                ('pets', models.IntegerField(verbose_name='Кол-во питомцев')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.properties')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
