# Generated by Django 4.0.6 on 2022-08-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookings_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к бронированию'),
        ),
    ]
