# Generated by Django 4.0.6 on 2022-10-06 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_config_delete_configs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Config',
            new_name='Configs',
        ),
    ]
